version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    networks: [monitoring]

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    command: [--config.file=/config/blackbox.yml]
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml:ro
    networks: [monitoring]

  # Optional local target to practice on
  mocksite:
    image: nginx:alpine
    container_name: mocksite
    ports:
      - "8088:80"
    networks: [monitoring]

volumes:
  prom_data:

networks:
  monitoring:
    external: true